# Generated by Django 2.2.24 on 2021-07-21 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drogue_nom', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Risque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_risque', models.IntegerField(default=0, verbose_name='Nombre de risques')),
                ('drogue_lien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Drogue')),
            ],
        ),
        migrations.CreateModel(
            name='Asso_Risq_Drog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liste_risques', models.TextField(max_length=200, verbose_name='Liste de risques')),
                ('drogue_lien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Drogue')),
                ('risque_lien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Risque')),
            ],
        ),
    ]
